/**
 * Handoff artifact — portable cross-agent briefing written at session_end.
 *
 * Automaticity Law: the file appears at projects/<slug>/handoff.md automatically
 * every session_end; no new MCP tool, no agent prompt needed.
 *
 * Budget: HARD LIMIT 2200 chars (~500 tokens). Content is truncated at word
 * boundaries and sections are omitted when empty.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { readP0Corrections } from "../storage/corrections.js";
import { readBehaviorPolicies } from "../storage/behavior-policies.js";
import { readInsightsIndex } from "../palace/insights-index.js";
import { readIdentity } from "../palace/identity.js";
import { ensureDir } from "../storage/fs-utils.js";
import { projectSubPath } from "../storage/paths.js";
import { scrubForCloud, fenceMemory } from "../storage/content-guard.js";
import { readTierCandidates } from "../retrieval/candidates.js";

const HARD_BUDGET = 2200;

/**
 * Truncate a string at word boundary, appending "…" if truncated.
 */
function truncateAt(text: string, maxChars: number): string {
  if (text.length <= maxChars) return text;
  const cut = text.lastIndexOf(" ", maxChars - 1);
  const boundary = cut > 0 ? cut : maxChars;
  return text.slice(0, boundary) + "…";
}

/**
 * Extract the first meaningful (non-heading, non-blank) line from a markdown string.
 * Returns empty string when nothing is found.
 */
function firstMeaningfulLine(md: string): string {
  for (const line of md.split("\n")) {
    const t = line.trim();
    if (t && !t.startsWith("#") && !t.startsWith(">") && !t.startsWith("---")) {
      return t;
    }
  }
  return "";
}

/**
 * Local-date string in YYYY-MM-DD format (system TZ).
 */
function localDate(): string {
  return new Date().toLocaleDateString("sv"); // 'sv' locale gives YYYY-MM-DD
}

export interface HandoffResult {
  path: string;
  tokens_estimate: number;
}

/**
 * Generate the handoff markdown for a project.
 * Pure function — reads stores, returns a string.
 * Never throws: missing stores produce empty sections which are omitted.
 */
export function generateHandoff(slug: string): string {
  const date = localDate();

  // ── Header ────────────────────────────────────────────────────────────────
  // Structural metadata (slug, date) — not retrieved memory. Fixed, never
  // fenced.
  const header = `# Handoff — ${slug} (${date})`;

  // ── Footer ────────────────────────────────────────────────────────────────
  // AgentRecall's own instruction to the HUMAN operator about the artifact
  // itself ("paste into any agent") — not retrieved memory either. Fixed,
  // never fenced.
  const footer = "\n---\n*Generated by AgentRecall session_end · paste into any agent*";

  // ── Memory-bearing sections (P1 fence, TOW2-388) ───────────────────────────
  // Everything below quotes retrieved corrections/policies/journal/insights
  // text — the red-team report's CRITICAL-1 finding named this exact file
  // ("a legitimate product feature whose entire purpose is 'copy this into
  // a fresh agent' now carries the injection... as its payload") as a proven
  // exploit path. Collected into `sectionLines` and fenced as ONE block
  // before assembly with the header/footer above.
  const sectionLines: string[] = [];

  // ── Intention ─────────────────────────────────────────────────────────────
  try {
    const identity = readIdentity(slug);
    let intention = firstMeaningfulLine(identity);
    // identity.md often already starts with "**Intention:** ..." — strip the
    // prefix so the template's own label doesn't double it.
    if (intention) intention = intention.replace(/^\*{0,2}Intention:?\*{0,2}\s*/i, "");
    if (intention) {
      sectionLines.push(`**Intention:** ${intention}`);
      sectionLines.push("");
    }
  } catch { /* omit */ }

  // ── Binding rules (P0 corrections, ≤5) ───────────────────────────────────
  try {
    const p0 = readP0Corrections(slug).slice(0, 5);
    if (p0.length > 0) {
      sectionLines.push("## Binding rules");
      for (const c of p0) {
        sectionLines.push(`- ${c.rule}`);
      }
      sectionLines.push("");
    }
  } catch { /* omit */ }

  // ── Behavior policies (≤3) ────────────────────────────────────────────────
  try {
    const { rules } = readBehaviorPolicies(slug);
    const top = rules.slice(0, 3);
    if (top.length > 0) {
      sectionLines.push("## Behavior policies");
      for (const r of top) {
        sectionLines.push(`- **${r.name}**: ${r.do}`);
      }
      sectionLines.push("");
    }
  } catch { /* omit */ }

  // ── Active blockers (from latest journal "## Blockers" section) ───────────
  // Identity-trust (P0 trust-class closure, 2026-08-30, wave/pipe-p0-trustclass):
  // was a raw fs.readFileSync of the latest journal file with ZERO rescue-tag
  // check — for a file whose entire purpose is "paste this into a fresh
  // agent" (see this file's own header comment), a hijacked card's
  // fabricated "blockers"/"next steps" would be copied VERBATIM into every
  // future session's handoff. Routed through readTierCandidates — already
  // trust-tagged + safe-by-default (drops untrusted candidates).
  try {
    const candidates = readTierCandidates("journal", slug);
    if (candidates.length > 0) {
      const content = candidates[0].content;
      // extractSection expects the SECTION_HEADERS map key; check if a
      // "## Blockers" heading is present by scanning directly (no SECTION_HEADERS key).
      const blockerIdx = content.indexOf("## Blockers");
      if (blockerIdx !== -1) {
        const section = content.slice(blockerIdx);
        const blockerLines = section.split("\n");
        const body: string[] = [];
        for (let i = 1; i < blockerLines.length; i++) {
          if (blockerLines[i].startsWith("## ")) break;
          const t = blockerLines[i].trim();
          if (t) body.push(t);
        }
        if (body.length > 0) {
          sectionLines.push("## Active blockers");
          sectionLines.push(body.slice(0, 5).join("\n"));
          sectionLines.push("");
        }
      }
    }
  } catch { /* omit */ }

  // ── Top insights (≤3, highest confirmed_count for this project) ───────────
  try {
    const index = readInsightsIndex();
    const projectInsights = index.insights
      .filter((i) => !i.projects || i.projects.length === 0 || i.projects.includes(slug))
      .sort((a, b) => b.confirmed_count - a.confirmed_count)
      .slice(0, 3);
    if (projectInsights.length > 0) {
      sectionLines.push("## Top insights");
      for (const ins of projectInsights) {
        sectionLines.push(`- ${ins.title} (confirmed ×${ins.confirmed_count})`);
      }
      sectionLines.push("");
    }
  } catch { /* omit */ }

  // ── Trajectory (## Next from newest journal) ──────────────────────────────
  // Identity-trust (P0 trust-class closure, 2026-08-30, wave/pipe-p0-trustclass):
  // same fix as the Blockers section above — routed through
  // readTierCandidates instead of a raw fs.readFileSync.
  try {
    const candidates = readTierCandidates("journal", slug);
    if (candidates.length > 0) {
      const content = candidates[0].content;
      // Use extractSection for the "next" key if available; fall back to raw scan.
      let nextText: string | null = null;
      const nextIdx = content.indexOf("## Next");
      if (nextIdx !== -1) {
        const section = content.slice(nextIdx);
        const nextLines = section.split("\n");
        const body: string[] = [];
        for (let i = 1; i < nextLines.length; i++) {
          if (nextLines[i].startsWith("## ")) break;
          const t = nextLines[i].trim();
          if (t) body.push(t);
        }
        if (body.length > 0) {
          nextText = body.join(" ");
        }
      }
      if (nextText) {
        sectionLines.push("## Trajectory");
        sectionLines.push(truncateAt(nextText, 300));
        sectionLines.push("");
      }
    }
  } catch { /* omit */ }

  // ── Budget enforcement ─────────────────────────────────────────────────────
  // HARD LIMIT: output MUST NOT exceed HARD_BUDGET characters. Truncation
  // happens on the UNFENCED section body so the byte budget accounts for the
  // fence's own fixed overhead (open+close markers), not the other way
  // around — otherwise a body that exactly fills the budget pre-fence would
  // push the final fenced+header+footer assembly over HARD_BUDGET.
  let sectionBody = sectionLines.join("\n").trimEnd();
  // fenceMemory("x").length - 1 == combined length of the open+close marker
  // lines (+ their separating newlines) for any 1-char payload — a generic
  // way to measure the fence's fixed overhead without hardcoding its format.
  const fenceOverhead = fenceMemory("x").length - 1;
  // Fix (review LOW, class-sweep follow-up): assembly below joins header and
  // fencedBody with "\n\n" (TWO newlines), not one — this accounted for only
  // one, undercounting fixedOverhead by 1 char. A body sized to exactly fill
  // budgetForSectionBody could therefore push the final assembly 1 char past
  // HARD_BUDGET before the line-223 last-resort slice caught it (cosmetic:
  // the slice still enforces the hard ceiling, but the pre-slice math was off).
  const fixedOverhead = header.length + 2 /* \n\n between header and body */ + footer.length + fenceOverhead;
  const budgetForSectionBody = HARD_BUDGET - fixedOverhead;
  if (sectionBody.length > budgetForSectionBody) {
    sectionBody = truncateAt(sectionBody, Math.max(0, budgetForSectionBody));
  }

  const fencedBody = fenceMemory(sectionBody);
  let result = fencedBody ? `${header}\n\n${fencedBody}${footer}` : `${header}\n${footer}`;

  // Assertion: enforce hard budget (catches regressions in section growth,
  // e.g. a future section that doesn't route through sectionLines/the
  // budget check above).
  if (result.length > HARD_BUDGET) {
    // Last-resort hard slice at word boundary.
    result = truncateAt(result, HARD_BUDGET);
  }

  return result;
}

/**
 * Write the handoff file for a project atomically.
 * Returns path and rough token estimate (chars / 4).
 * Never throws — errors are propagated to caller for fire-and-forget swallowing.
 */
export function writeHandoff(slug: string): HandoffResult {
  // F2 fix (independent review, 2026-07-20): was a local naive sanitizer
  // (no lowercase, no existing-dir reuse) — routes through paths.ts now, so
  // handoff.md always lands next to the SAME project's journal/palace.
  const projectDir = projectSubPath(slug || "unnamed");
  ensureDir(projectDir);

  const handoffPath = path.join(projectDir, "handoff.md");
  // handoff.md is never synced to Supabase (this module has no syncToSupabase
  // call at all) and is the explicit "paste into any agent" artifact — the
  // highest-exposure local write in the codebase before this fix, since it
  // shipped with NO scrub of any kind, cloud or local. Its sections quote
  // corrections/behavior-policies/journal-blockers/insights text; scrub the
  // FINAL assembled string as defense-in-depth even though those sources are
  // now scrubbed at their own write sites, so a source that predates this fix
  // (or a future section this function grows) still can't leak raw secrets or
  // an injection payload into whatever agent the human pastes this into.
  const content = scrubForCloud(generateHandoff(slug));

  // Atomic write: tmp + rename (POSIX-atomic).
  const tmp = `${handoffPath}.tmp.${process.pid}.${Date.now()}`;
  fs.writeFileSync(tmp, content, { encoding: "utf-8", mode: 0o600 });
  fs.renameSync(tmp, handoffPath);

  return {
    path: handoffPath,
    tokens_estimate: Math.ceil(content.length / 4),
  };
}
